import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    appSubtitle: "Vocabulary learning app",
    routeLoading: "Learning English",
    routeLoadingHint: "Preparing your next lesson",
    home: "Home",
    lessons: "Lessons",
    learnVocabulary: "Learn Vocabulary",
    practiceVocabulary: "Practice Vocabulary",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    admin: "Admin",
    vocabularyPlatform: "Vocabulary Learning Platform",
    heroCopy:
      "Learn English vocabulary lesson by lesson with Bengali meanings, useful examples, and a clean search experience for quick revision.",
    startLearning: "Start Learning",
    searchVocabulary: "Search Vocabulary",
    forStudents: "For Students",
    learnSimpleSteps: "Learn with simple steps",
    chooseLesson: "Choose a segment and bundle",
    readVocabulary: "Read vocabulary",
    searchReview: "Search and review",
    organizedVocabulary: "Organized vocabulary",
    lessonsFeatureCopy:
      "Browse segments such as Daily Use, Admission Exam, and Professional Field, then open a bundle to view its words.",
    viewLessons: "View segments",
    search: "Search",
    findWordsQuickly: "Find words quickly",
    searchFeatureCopy:
      "Search vocabulary by English word or Bengali meaning and open the details page for examples when available.",
    searchWords: "Search words",
    allLessons: "All Lessons",
    manageLessons: "Manage Segments",
    addLesson: "Add Bundle",
    editLesson: "Edit Bundle",
    loadingLessons: "Loading bundle...",
    noLessonsFound: "No lessons found",
    addFirstLesson: "Add your first lesson to start building the vocabulary database.",
    noLessonsAvailable: "No lessons are available yet.",
    viewVocabulary: "View Vocabulary",
    edit: "Edit",
    delete: "Delete",
    noDescription: "No description added yet.",
    lessonVocabulary: "Bundle Vocabulary",
    loadingLessonVocabulary: "Loading bundle vocabulary...",
    backToLessons: "Back to Segments",
    noVocabularyFound: "No vocabulary found",
    lessonNoVocabulary: "This bundle does not contain any vocabulary yet.",
    searchVocabularyHeading: "Search Vocabulary",
    manageVocabulary: "Manage Vocabulary",
    addVocabulary: "Add Vocabulary",
    findWord: "Find a word",
    findVocabularyRecord: "Find a vocabulary record",
    searchPanelCopy:
      "Search using an English word or Bengali meaning. Results update from the vocabulary database.",
    vocabularySearch: "Vocabulary search",
    searchPlaceholder: "Example: Hello, মা, Rice",
    reset: "Reset",
    try: "Try:",
    loadingVocabulary: "Loading vocabulary...",
    noMatchingWords: "No matching words found",
    noVocabularyAvailable: "Vocabulary records are not available yet.",
    addVocabularyPrompt: "Add vocabulary records to start building the database.",
    noResultMatched: "No result matched",
    wordCount: "word(s)",
    resultCount: "result(s)",
    viewDetails: "View Details",
    pronunciation: "Pronunciation:",
    meaning: "Meaning",
    wordDetails: "Word Details",
    loadingWordDetails: "Loading word details...",
    backToVocabulary: "Back to Vocabulary",
    englishWord: "English Word:",
    bengaliMeaning: "Bengali Meaning:",
    lessonTitle: "Bundle:",
    exampleSentence: "Example Sentence:",
    learnUsingCards: "Learn Using Cards",
    learnCardsCopy: "Choose a bundle, then practice each vocabulary word with a flip card.",
    step1: "Step 1",
    step2: "Step 2",
    selectLesson: "Select Bundle",
    vocabularyCards: "Vocabulary Cards",
    practiceThisLesson: "Practice this bundle.",
    selectLessonFirst: "Select a bundle first to see vocabulary cards.",
    noLessonCards: "No vocabulary is available for this bundle.",
    clickPractice: "Click to practice",
    vocabulary: "Vocabulary",
    details: "Details",
    clickFlip: "Click card to flip",
    clickFlipBack: "Click card to flip back",
    closeCard: "Close card",
    contentManagement: "Content Management",
    adminDashboardCopy:
      "An overview of your segments, bundles, and vocabulary, with quick actions to manage content.",
    lessonAdminCopy: "Add new lessons, view the lesson list, and update lesson details.",
    vocabularyAdminCopy: "Add vocabulary, search all records, and update word information.",
    title: "Title",
    description: "Description",
    optional: "optional",
    saveLesson: "Save Bundle",
    saving: "Saving...",
    updateLesson: "Update Bundle",
    updating: "Updating...",
    lesson: "Bundle",
    selectALesson: "Select a bundle",
    englishWordLabel: "English Word",
    bengaliMeaningLabel: "Bengali Meaning",
    exampleOptional: "Example Sentence (optional)",
    saveVocabulary: "Save Vocabulary",
    updateVocabulary: "Update Vocabulary",
    browseLessons: "Browse Segments",
    adminPanel: "Admin Panel",
    project: "Project",
    techStack: "React + Django REST",
    mysqlDatabase: "MySQL Database",
    week3Scope: "Week 3 Final Scope",
    toggleNavigation: "Toggle navigation menu",
    searchSuggestions: "Search suggestions",
    builtFor: "Built for vocabulary learning and content management",
    projectLine:
      "A responsive DBMS project for organizing English vocabulary into lessons with Bengali meanings, examples, search, and content management.",
    partOfSpeech: "Part of Speech:",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    allDifficulties: "All difficulties",
    synonyms: "Synonyms:",
    antonyms: "Antonyms:",
    synonymsOptional: "Synonyms (optional)",
    antonymsOptional: "Antonyms (optional)",
    commaSeparatedPlaceholder: "Comma-separated, e.g. Hi, Hey",
    selectOptional: "Select (optional)",
    noun: "Noun",
    verb: "Verb",
    adjective: "Adjective",
    adverb: "Adverb",
    pronoun: "Pronoun",
    preposition: "Preposition",
    conjunction: "Conjunction",
    interjection: "Interjection",
    segments: "Segments",
    allSegments: "All Segments",
    manageSegments: "Manage Segments",
    segmentsCopy: "Segments group vocabulary bundles by purpose, such as Daily Use, Admission Exam, or Professional Field.",
    addSegment: "Add Segment",
    editSegment: "Edit Segment",
    loadingSegments: "Loading segments...",
    noSegmentsFound: "No segments found",
    addFirstSegment: "Add your first segment to start organizing bundles.",
    noSegmentsAvailable: "No segments are available yet.",
    segmentName: "Segment Name",
    saveSegment: "Save Segment",
    updateSegment: "Update Segment",
    backToSegments: "Back to Segments",
    segment: "Segment",
    selectASegment: "Select a segment",
    bundles: "bundles",
    viewBundles: "View Bundles",
    addBundle: "Add Bundle",
    loadingBundles: "Loading bundles...",
    noBundlesFound: "No bundles found",
    addFirstBundle: "Add your first bundle to this segment.",
    noBundlesAvailable: "No bundles are available in this segment yet.",
    words: "words",
    wordsLearned: "words learned",
    bundleComplete: "Bundle complete",
    segmentComplete: "All bundles in this segment are complete. Great work!",
    segmentAdminCopy: "Create segments like Daily Use, Admission Exam, or Professional Field to group bundles.",
    markAsKnown: "I know this word",
    markAsUnknown: "Unmark as known",
    addVocabularyCopy: "Pick a segment and add the word — it's placed into the current open bundle automatically, or a new bundle is created once the last one reaches 20 words.",
    autoGenerated: "optional, auto-generated",
    autoGeneratedPlaceholder: "Leave blank to auto-name this bundle",
    open: "open",
    full: "full",
    capacityUsed: "capacity used",
    quickActions: "Quick Actions",
    segmentOverview: "Segment Overview",
    dashboard: "Dashboard",
    studentView: "Student View",
    backToSite: "Back to Site",
    backToSiteCopy: "View the public website",
    welcomeAdmin: "Welcome back, Admin",
    recentSegments: "Recent Segments",
    bundleStatus: "Bundle Status",
    recentVocabulary: "Recently Added Words",
    noVocabularyYet: "No vocabulary added yet.",
    allBundles: "All Bundles",
    allBundlesCopy: "Every bundle across all segments, in one place.",
    bundlesLabel: "Bundles",
    allPartsOfSpeech: "All parts of speech",
    previousPage: "Previous",
    nextPage: "Next",
    page: "Page",
    of: "of",
    practiceHubCopy: "Choose how you want to practice this bundle.",
    viewWordList: "View Word List",
    flashCards: "Flash Cards",
    flashCardsCopy: "Learn the words",
    matchWords: "Match Words with Meanings",
    matchWordsCopy: "Test your memory",
    useInSentence: "Use in a Sentence",
    useInSentenceCopy: "Practice usage",
    synonymAntonymTest: "Synonym & Antonym Test",
    optionalExam: "Optional Exam",
    topScore: "Top Score",
    questionsLabel: "questions",
    comingSoon: "Coming soon",
    wordLabel: "Word",
    meaningLabel: "Meaning (Bengali)",
    remove: "Remove",
    addRow: "+ Add",
    tapToSeeMeaning: "Tap each word to see the meaning",
    seeSynonymsAntonyms: "See Synonyms & Antonyms",
    hide: "Hide",
    noSynonymsAntonyms: "No synonyms or antonyms added for this word yet.",
    backToBundle: "Back to Bundle",
  },
  bn: {
    appSubtitle: "শব্দভান্ডার শেখার অ্যাপ",
    routeLoading: "ইংরেজি শিখছি",
    routeLoadingHint: "আপনার পরের লেসন প্রস্তুত হচ্ছে",
    home: "হোম",
    lessons: "লেসন",
    learnVocabulary: "শব্দ শিখুন",
    practiceVocabulary: "শব্দ অনুশীলন",
    language: "ভাষা",
    english: "English",
    bangla: "বাংলা",
    admin: "অ্যাডমিন",
    vocabularyPlatform: "শব্দভান্ডার শেখার প্ল্যাটফর্ম",
    heroCopy:
      "বাংলা অর্থ, দরকারি উদাহরণ এবং সহজ সার্চ সুবিধার মাধ্যমে লেসন ধরে ইংরেজি শব্দ শিখুন।",
    startLearning: "শেখা শুরু করুন",
    searchVocabulary: "শব্দ খুঁজুন",
    forStudents: "শিক্ষার্থীদের জন্য",
    learnSimpleSteps: "সহজ ধাপে শিখুন",
    chooseLesson: "একটি সেগমেন্ট ও বান্ডেল বেছে নিন",
    readVocabulary: "শব্দ পড়ুন",
    searchReview: "সার্চ করে রিভিশন দিন",
    organizedVocabulary: "গোছানো শব্দভান্ডার",
    lessonsFeatureCopy:
      "Greetings, Family, Food-এর মতো লেসন ব্রাউজ করুন এবং প্রতিটি লেসনের শব্দগুলো দেখুন।",
    viewLessons: "সেগমেন্ট দেখুন",
    search: "সার্চ",
    findWordsQuickly: "দ্রুত শব্দ খুঁজুন",
    searchFeatureCopy:
      "ইংরেজি শব্দ বা বাংলা অর্থ দিয়ে সার্চ করুন এবং দরকার হলে বিস্তারিত পেজ খুলুন।",
    searchWords: "শব্দ সার্চ করুন",
    allLessons: "সব লেসন",
    manageLessons: "সেগমেন্ট ম্যানেজ করুন",
    addLesson: "বান্ডেল যোগ করুন",
    editLesson: "বান্ডেল এডিট করুন",
    loadingLessons: "বান্ডেল লোড হচ্ছে...",
    noLessonsFound: "কোনো লেসন পাওয়া যায়নি",
    addFirstLesson: "শব্দভান্ডার ডাটাবেস শুরু করতে প্রথম লেসন যোগ করুন।",
    noLessonsAvailable: "এখনো কোনো লেসন নেই।",
    viewVocabulary: "শব্দ দেখুন",
    edit: "এডিট",
    delete: "ডিলিট",
    noDescription: "এখনো কোনো বর্ণনা যোগ করা হয়নি।",
    lessonVocabulary: "লেসনের শব্দ",
    loadingLessonVocabulary: "বান্ডেলের শব্দ লোড হচ্ছে...",
    backToLessons: "সেগমেন্টে ফিরে যান",
    noVocabularyFound: "কোনো শব্দ পাওয়া যায়নি",
    lessonNoVocabulary: "এই লেসনে এখনো কোনো শব্দ নেই।",
    searchVocabularyHeading: "শব্দ সার্চ করুন",
    manageVocabulary: "শব্দ ম্যানেজ করুন",
    addVocabulary: "শব্দ যোগ করুন",
    findWord: "শব্দ খুঁজুন",
    findVocabularyRecord: "শব্দের রেকর্ড খুঁজুন",
    searchPanelCopy:
      "ইংরেজি শব্দ বা বাংলা অর্থ দিয়ে সার্চ করুন। ফলাফল ডাটাবেস থেকে আপডেট হবে।",
    vocabularySearch: "শব্দ সার্চ",
    searchPlaceholder: "যেমন: Hello, মা, Rice",
    reset: "রিসেট",
    try: "চেষ্টা করুন:",
    loadingVocabulary: "শব্দ লোড হচ্ছে...",
    noMatchingWords: "মিল পাওয়া যায়নি",
    noVocabularyAvailable: "এখনো কোনো শব্দ নেই।",
    addVocabularyPrompt: "ডাটাবেস তৈরি করতে শব্দ যোগ করুন।",
    noResultMatched: "কোনো ফল মেলেনি",
    wordCount: "টি শব্দ",
    resultCount: "টি ফলাফল",
    viewDetails: "বিস্তারিত দেখুন",
    pronunciation: "উচ্চারণ:",
    meaning: "অর্থ",
    wordDetails: "শব্দের বিস্তারিত",
    loadingWordDetails: "শব্দের বিস্তারিত লোড হচ্ছে...",
    backToVocabulary: "শব্দ পেজে ফিরে যান",
    englishWord: "ইংরেজি শব্দ:",
    bengaliMeaning: "বাংলা অর্থ:",
    lessonTitle: "লেসনের নাম:",
    exampleSentence: "উদাহরণ বাক্য:",
    learnUsingCards: "কার্ড দিয়ে শিখুন",
    learnCardsCopy: "একটি লেসন বেছে নিন, তারপর ফ্লিপ কার্ড দিয়ে শব্দ অনুশীলন করুন।",
    step1: "ধাপ ১",
    step2: "ধাপ ২",
    selectLesson: "বান্ডেল নির্বাচন করুন",
    vocabularyCards: "শব্দ কার্ড",
    practiceThisLesson: "এই বান্ডেল অনুশীলন করুন।",
    selectLessonFirst: "শব্দ কার্ড দেখতে আগে একটি বান্ডেল নির্বাচন করুন।",
    noLessonCards: "এই বান্ডেলে কোনো শব্দ নেই।",
    clickPractice: "অনুশীলন করতে ক্লিক করুন",
    vocabulary: "শব্দ",
    details: "বিস্তারিত",
    clickFlip: "ফ্লিপ করতে কার্ডে ক্লিক করুন",
    clickFlipBack: "ফিরে যেতে কার্ডে ক্লিক করুন",
    closeCard: "কার্ড বন্ধ করুন",
    contentManagement: "কনটেন্ট ম্যানেজমেন্ট",
    adminDashboardCopy:
      "তোমার সেগমেন্ট, বান্ডেল আর ভোকাবুলারির একটা ওভারভিউ, সাথে কনটেন্ট ম্যানেজ করার দ্রুত অপশন।",
    lessonAdminCopy: "নতুন লেসন যোগ করুন, লেসন তালিকা দেখুন এবং লেসনের তথ্য আপডেট করুন।",
    vocabularyAdminCopy: "শব্দ যোগ করুন, সব রেকর্ড সার্চ করুন এবং শব্দের তথ্য আপডেট করুন।",
    title: "শিরোনাম",
    description: "বর্ণনা",
    optional: "ঐচ্ছিক",
    saveLesson: "বান্ডেল সেভ করুন",
    saving: "সেভ হচ্ছে...",
    updateLesson: "বান্ডেল আপডেট করুন",
    updating: "আপডেট হচ্ছে...",
    lesson: "বান্ডেল",
    selectALesson: "একটি বান্ডেল নির্বাচন করুন",
    englishWordLabel: "ইংরেজি শব্দ",
    bengaliMeaningLabel: "বাংলা অর্থ",
    exampleOptional: "উদাহরণ বাক্য (ঐচ্ছিক)",
    saveVocabulary: "শব্দ সেভ করুন",
    updateVocabulary: "শব্দ আপডেট করুন",
    browseLessons: "সেগমেন্ট ব্রাউজ করুন",
    adminPanel: "অ্যাডমিন প্যানেল",
    project: "প্রজেক্ট",
    techStack: "React + Django REST",
    mysqlDatabase: "MySQL ডাটাবেস",
    week3Scope: "Week 3 Final Scope",
    toggleNavigation: "নেভিগেশন মেনু খুলুন/বন্ধ করুন",
    searchSuggestions: "সার্চ সাজেশন",
    builtFor: "শব্দ শেখা এবং কনটেন্ট ম্যানেজমেন্টের জন্য তৈরি",
    projectLine:
      "বাংলা অর্থ, উদাহরণ, সার্চ এবং কনটেন্ট ম্যানেজমেন্টসহ ইংরেজি শব্দ লেসন অনুযায়ী সাজানোর একটি রেসপনসিভ DBMS প্রজেক্ট।",
    partOfSpeech: "পদ (Part of Speech):",
    difficulty: "কঠিনতার মাত্রা",
    easy: "সহজ",
    medium: "মাঝারি",
    hard: "কঠিন",
    allDifficulties: "সব স্তর",
    synonyms: "প্রতিশব্দ:",
    antonyms: "বিপরীত শব্দ:",
    synonymsOptional: "প্রতিশব্দ (ঐচ্ছিক)",
    antonymsOptional: "বিপরীত শব্দ (ঐচ্ছিক)",
    commaSeparatedPlaceholder: "কমা দিয়ে আলাদা করুন, যেমন: Hi, Hey",
    selectOptional: "নির্বাচন করুন (ঐচ্ছিক)",
    noun: "বিশেষ্য",
    verb: "ক্রিয়া",
    adjective: "বিশেষণ",
    adverb: "ক্রিয়া বিশেষণ",
    pronoun: "সর্বনাম",
    preposition: "পদান্বয়ী অব্যয়",
    conjunction: "সংযোজক অব্যয়",
    interjection: "আবেগসূচক শব্দ",
    segments: "সেগমেন্ট",
    allSegments: "সব সেগমেন্ট",
    manageSegments: "সেগমেন্ট ম্যানেজ করুন",
    segmentsCopy: "সেগমেন্ট দিয়ে শব্দ বান্ডেল উদ্দেশ্য অনুযায়ী ভাগ করা হয় — যেমন দৈনন্দিন ব্যবহার, ভর্তি পরীক্ষা, বা পেশাগত ক্ষেত্র।",
    addSegment: "সেগমেন্ট যোগ করুন",
    editSegment: "সেগমেন্ট এডিট করুন",
    loadingSegments: "সেগমেন্ট লোড হচ্ছে...",
    noSegmentsFound: "কোনো সেগমেন্ট পাওয়া যায়নি",
    addFirstSegment: "বান্ডেল গুছিয়ে রাখতে প্রথম সেগমেন্ট যোগ করুন।",
    noSegmentsAvailable: "এখনো কোনো সেগমেন্ট নেই।",
    segmentName: "সেগমেন্টের নাম",
    saveSegment: "সেগমেন্ট সেভ করুন",
    updateSegment: "সেগমেন্ট আপডেট করুন",
    backToSegments: "সেগমেন্টে ফিরে যান",
    segment: "সেগমেন্ট",
    selectASegment: "একটি সেগমেন্ট নির্বাচন করুন",
    bundles: "বান্ডেল",
    viewBundles: "বান্ডেল দেখুন",
    addBundle: "বান্ডেল যোগ করুন",
    loadingBundles: "বান্ডেল লোড হচ্ছে...",
    noBundlesFound: "কোনো বান্ডেল পাওয়া যায়নি",
    addFirstBundle: "এই সেগমেন্টে প্রথম বান্ডেল যোগ করুন।",
    noBundlesAvailable: "এই সেগমেন্টে এখনো কোনো বান্ডেল নেই।",
    words: "শব্দ",
    wordsLearned: "শব্দ শেখা হয়েছে",
    bundleComplete: "বান্ডেল সম্পূর্ণ",
    segmentComplete: "এই সেগমেন্টের সব বান্ডেল সম্পূর্ণ হয়েছে। দারুণ কাজ!",
    segmentAdminCopy: "বান্ডেল গুছিয়ে রাখতে দৈনন্দিন ব্যবহার, ভর্তি পরীক্ষা, পেশাগত ক্ষেত্রের মতো সেগমেন্ট তৈরি করুন।",
    markAsKnown: "আমি এই শব্দটি জানি",
    markAsUnknown: "জানা থেকে বাদ দিন",
    addVocabularyCopy: "একটি সেগমেন্ট বেছে নিয়ে শব্দ যোগ করুন — এটি স্বয়ংক্রিয়ভাবে খোলা বান্ডেলে যোগ হবে, আর শেষ বান্ডেলে ২০টা শব্দ পূর্ণ হলে নতুন বান্ডেল নিজে থেকেই তৈরি হবে।",
    autoGenerated: "ঐচ্ছিক, স্বয়ংক্রিয়ভাবে তৈরি হবে",
    autoGeneratedPlaceholder: "খালি রাখলে বান্ডেলের নাম নিজে থেকেই হবে",
    open: "খোলা",
    full: "পূর্ণ",
    capacityUsed: "ক্যাপাসিটি ব্যবহৃত",
    quickActions: "দ্রুত কাজ",
    segmentOverview: "সেগমেন্ট ওভারভিউ",
    dashboard: "ড্যাশবোর্ড",
    studentView: "স্টুডেন্ট ভিউ",
    backToSite: "সাইটে ফিরে যান",
    backToSiteCopy: "পাবলিক ওয়েবসাইট দেখুন",
    welcomeAdmin: "স্বাগতম, অ্যাডমিন",
    recentSegments: "সাম্প্রতিক সেগমেন্ট",
    bundleStatus: "বান্ডেল স্ট্যাটাস",
    recentVocabulary: "সম্প্রতি যোগ হওয়া শব্দ",
    noVocabularyYet: "এখনো কোনো শব্দ যোগ করা হয়নি।",
    allBundles: "সব বান্ডেল",
    allBundlesCopy: "সব সেগমেন্টের সব বান্ডেল একসাথে।",
    bundlesLabel: "বান্ডেল",
    allPartsOfSpeech: "সব পদ (Part of Speech)",
    previousPage: "আগের পেজ",
    nextPage: "পরের পেজ",
    page: "পেজ",
    of: "এর মধ্যে",
    practiceHubCopy: "এই বান্ডেলটা কীভাবে অনুশীলন করতে চাও বেছে নাও।",
    viewWordList: "শব্দের তালিকা দেখুন",
    flashCards: "ফ্ল্যাশ কার্ড",
    flashCardsCopy: "শব্দ শিখুন",
    matchWords: "শব্দ ও অর্থ মেলান",
    matchWordsCopy: "স্মৃতিশক্তি যাচাই করুন",
    useInSentence: "বাক্যে ব্যবহার করুন",
    useInSentenceCopy: "ব্যবহার অনুশীলন করুন",
    synonymAntonymTest: "প্রতিশব্দ ও বিপরীত শব্দ টেস্ট",
    optionalExam: "ঐচ্ছিক পরীক্ষা",
    topScore: "সর্বোচ্চ স্কোর",
    questionsLabel: "টি প্রশ্ন",
    comingSoon: "শীঘ্রই আসছে",
    wordLabel: "শব্দ",
    meaningLabel: "অর্থ (বাংলা)",
    remove: "বাদ দিন",
    addRow: "+ যোগ করুন",
    tapToSeeMeaning: "অর্থ দেখতে প্রতিটা শব্দে ট্যাপ করুন",
    seeSynonymsAntonyms: "প্রতিশব্দ ও বিপরীত শব্দ দেখুন",
    hide: "লুকান",
    noSynonymsAntonyms: "এই শব্দের জন্য এখনো কোনো প্রতিশব্দ/বিপরীত শব্দ যোগ করা হয়নি।",
    backToBundle: "বান্ডেলে ফিরে যান",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("ej-language") || "en");

  useEffect(() => {
    localStorage.setItem("ej-language", language);
    document.documentElement.lang = language === "bn" ? "bn" : "en";
  }, [language]);

  const value = useMemo(() => {
    function t(key) {
      return translations[language]?.[key] || translations.en[key] || key;
    }

    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "bn" : "en")),
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
