import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    appSubtitle: "Vocabulary learning app",
    routeLoading: "Learning English",
    routeLoadingHint: "Preparing your next lesson",
    home: "Home",
    lessons: "Lessons",
    learnVocabulary: "Learn Vocabulary",
    practiceVocabulary: "Practice Vocabulary",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    admin: "Admin",
    vocabularyPlatform: "Vocabulary Learning Platform",
    heroCopy:
      "Learn English vocabulary lesson by lesson with Bengali meanings, useful examples, and a clean search experience for quick revision.",
    startLearning: "Start Learning",
    searchVocabulary: "Search Vocabulary",
    forStudents: "For Students",
    learnSimpleSteps: "Learn with simple steps",
    chooseLesson: "Choose a lesson",
    readVocabulary: "Read vocabulary",
    searchReview: "Search and review",
    organizedVocabulary: "Organized vocabulary",
    lessonsFeatureCopy:
      "Browse lessons such as greetings, family, and food, then open each lesson to view its related words.",
    viewLessons: "View lessons",
    search: "Search",
    findWordsQuickly: "Find words quickly",
    searchFeatureCopy:
      "Search vocabulary by English word or Bengali meaning and open the details page for examples when available.",
    searchWords: "Search words",
    allLessons: "All Lessons",
    manageLessons: "Manage Lessons",
    addLesson: "Add Lesson",
    editLesson: "Edit Lesson",
    loadingLessons: "Loading lessons...",
    noLessonsFound: "No lessons found",
    addFirstLesson: "Add your first lesson to start building the vocabulary database.",
    noLessonsAvailable: "No lessons are available yet.",
    viewVocabulary: "View Vocabulary",
    edit: "Edit",
    delete: "Delete",
    noDescription: "No description added yet.",
    lessonVocabulary: "Lesson Vocabulary",
    loadingLessonVocabulary: "Loading lesson vocabulary...",
    backToLessons: "Back to Lessons",
    noVocabularyFound: "No vocabulary found",
    lessonNoVocabulary: "This lesson does not contain any vocabulary yet.",
    searchVocabularyHeading: "Search Vocabulary",
    manageVocabulary: "Manage Vocabulary",
    addVocabulary: "Add Vocabulary",
    findWord: "Find a word",
    findVocabularyRecord: "Find a vocabulary record",
    searchPanelCopy:
      "Search using an English word or Bengali meaning. Results update from the vocabulary database.",
    vocabularySearch: "Vocabulary search",
    searchPlaceholder: "Example: Hello, মা, Rice",
    reset: "Reset",
    try: "Try:",
    loadingVocabulary: "Loading vocabulary...",
    noMatchingWords: "No matching words found",
    noVocabularyAvailable: "Vocabulary records are not available yet.",
    addVocabularyPrompt: "Add vocabulary records to start building the database.",
    noResultMatched: "No result matched",
    wordCount: "word(s)",
    resultCount: "result(s)",
    viewDetails: "View Details",
    pronunciation: "Pronunciation:",
    meaning: "Meaning",
    wordDetails: "Word Details",
    loadingWordDetails: "Loading word details...",
    backToVocabulary: "Back to Vocabulary",
    englishWord: "English Word:",
    bengaliMeaning: "Bengali Meaning:",
    lessonTitle: "Lesson Title:",
    exampleSentence: "Example Sentence:",
    learnUsingCards: "Learn Using Cards",
    learnCardsCopy: "Choose a lesson, then practice each vocabulary word with a flip card.",
    step1: "Step 1",
    step2: "Step 2",
    selectLesson: "Select Lesson",
    vocabularyCards: "Vocabulary Cards",
    practiceThisLesson: "Practice this lesson.",
    selectLessonFirst: "Select a lesson first to see vocabulary cards.",
    noLessonCards: "No vocabulary is available for this lesson.",
    clickPractice: "Click to practice",
    vocabulary: "Vocabulary",
    details: "Details",
    clickFlip: "Click card to flip",
    clickFlipBack: "Click card to flip back",
    closeCard: "Close card",
    contentManagement: "Content Management",
    adminDashboardCopy:
      "Manage lesson and vocabulary records with Create, View, and Update operations.",
    lessonAdminCopy: "Add new lessons, view the lesson list, and update lesson details.",
    vocabularyAdminCopy: "Add vocabulary, search all records, and update word information.",
    title: "Title",
    description: "Description",
    optional: "optional",
    saveLesson: "Save Lesson",
    saving: "Saving...",
    updateLesson: "Update Lesson",
    updating: "Updating...",
    lesson: "Lesson",
    selectALesson: "Select a lesson",
    englishWordLabel: "English Word",
    bengaliMeaningLabel: "Bengali Meaning",
    exampleOptional: "Example Sentence (optional)",
    saveVocabulary: "Save Vocabulary",
    updateVocabulary: "Update Vocabulary",
    browseLessons: "Browse Lessons",
    adminPanel: "Admin Panel",
    project: "Project",
    techStack: "React + Django REST",
    mysqlDatabase: "MySQL Database",
    week3Scope: "Week 3 Final Scope",
    toggleNavigation: "Toggle navigation menu",
    searchSuggestions: "Search suggestions",
    builtFor: "Built for vocabulary learning and content management",
    projectLine:
      "A responsive DBMS project for organizing English vocabulary into lessons with Bengali meanings, examples, search, and content management.",
    partOfSpeech: "Part of Speech:",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    allDifficulties: "All difficulties",
    synonyms: "Synonyms:",
    antonyms: "Antonyms:",
    synonymsOptional: "Synonyms (optional)",
    antonymsOptional: "Antonyms (optional)",
    commaSeparatedPlaceholder: "Comma-separated, e.g. Hi, Hey",
    selectOptional: "Select (optional)",
    noun: "Noun",
    verb: "Verb",
    adjective: "Adjective",
    adverb: "Adverb",
    pronoun: "Pronoun",
    preposition: "Preposition",
    conjunction: "Conjunction",
    interjection: "Interjection",
  },
  bn: {
    appSubtitle: "শব্দভান্ডার শেখার অ্যাপ",
    routeLoading: "ইংরেজি শিখছি",
    routeLoadingHint: "আপনার পরের লেসন প্রস্তুত হচ্ছে",
    home: "হোম",
    lessons: "লেসন",
    learnVocabulary: "শব্দ শিখুন",
    practiceVocabulary: "শব্দ অনুশীলন",
    language: "ভাষা",
    english: "English",
    bangla: "বাংলা",
    admin: "অ্যাডমিন",
    vocabularyPlatform: "শব্দভান্ডার শেখার প্ল্যাটফর্ম",
    heroCopy:
      "বাংলা অর্থ, দরকারি উদাহরণ এবং সহজ সার্চ সুবিধার মাধ্যমে লেসন ধরে ইংরেজি শব্দ শিখুন।",
    startLearning: "শেখা শুরু করুন",
    searchVocabulary: "শব্দ খুঁজুন",
    forStudents: "শিক্ষার্থীদের জন্য",
    learnSimpleSteps: "সহজ ধাপে শিখুন",
    chooseLesson: "একটি লেসন বেছে নিন",
    readVocabulary: "শব্দ পড়ুন",
    searchReview: "সার্চ করে রিভিশন দিন",
    organizedVocabulary: "গোছানো শব্দভান্ডার",
    lessonsFeatureCopy:
      "Greetings, Family, Food-এর মতো লেসন ব্রাউজ করুন এবং প্রতিটি লেসনের শব্দগুলো দেখুন।",
    viewLessons: "লেসন দেখুন",
    search: "সার্চ",
    findWordsQuickly: "দ্রুত শব্দ খুঁজুন",
    searchFeatureCopy:
      "ইংরেজি শব্দ বা বাংলা অর্থ দিয়ে সার্চ করুন এবং দরকার হলে বিস্তারিত পেজ খুলুন।",
    searchWords: "শব্দ সার্চ করুন",
    allLessons: "সব লেসন",
    manageLessons: "লেসন ম্যানেজ করুন",
    addLesson: "লেসন যোগ করুন",
    editLesson: "লেসন এডিট করুন",
    loadingLessons: "লেসন লোড হচ্ছে...",
    noLessonsFound: "কোনো লেসন পাওয়া যায়নি",
    addFirstLesson: "শব্দভান্ডার ডাটাবেস শুরু করতে প্রথম লেসন যোগ করুন।",
    noLessonsAvailable: "এখনো কোনো লেসন নেই।",
    viewVocabulary: "শব্দ দেখুন",
    edit: "এডিট",
    delete: "ডিলিট",
    noDescription: "এখনো কোনো বর্ণনা যোগ করা হয়নি।",
    lessonVocabulary: "লেসনের শব্দ",
    loadingLessonVocabulary: "লেসনের শব্দ লোড হচ্ছে...",
    backToLessons: "লেসনে ফিরে যান",
    noVocabularyFound: "কোনো শব্দ পাওয়া যায়নি",
    lessonNoVocabulary: "এই লেসনে এখনো কোনো শব্দ নেই।",
    searchVocabularyHeading: "শব্দ সার্চ করুন",
    manageVocabulary: "শব্দ ম্যানেজ করুন",
    addVocabulary: "শব্দ যোগ করুন",
    findWord: "শব্দ খুঁজুন",
    findVocabularyRecord: "শব্দের রেকর্ড খুঁজুন",
    searchPanelCopy:
      "ইংরেজি শব্দ বা বাংলা অর্থ দিয়ে সার্চ করুন। ফলাফল ডাটাবেস থেকে আপডেট হবে।",
    vocabularySearch: "শব্দ সার্চ",
    searchPlaceholder: "যেমন: Hello, মা, Rice",
    reset: "রিসেট",
    try: "চেষ্টা করুন:",
    loadingVocabulary: "শব্দ লোড হচ্ছে...",
    noMatchingWords: "মিল পাওয়া যায়নি",
    noVocabularyAvailable: "এখনো কোনো শব্দ নেই।",
    addVocabularyPrompt: "ডাটাবেস তৈরি করতে শব্দ যোগ করুন।",
    noResultMatched: "কোনো ফল মেলেনি",
    wordCount: "টি শব্দ",
    resultCount: "টি ফলাফল",
    viewDetails: "বিস্তারিত দেখুন",
    pronunciation: "উচ্চারণ:",
    meaning: "অর্থ",
    wordDetails: "শব্দের বিস্তারিত",
    loadingWordDetails: "শব্দের বিস্তারিত লোড হচ্ছে...",
    backToVocabulary: "শব্দ পেজে ফিরে যান",
    englishWord: "ইংরেজি শব্দ:",
    bengaliMeaning: "বাংলা অর্থ:",
    lessonTitle: "লেসনের নাম:",
    exampleSentence: "উদাহরণ বাক্য:",
    learnUsingCards: "কার্ড দিয়ে শিখুন",
    learnCardsCopy: "একটি লেসন বেছে নিন, তারপর ফ্লিপ কার্ড দিয়ে শব্দ অনুশীলন করুন।",
    step1: "ধাপ ১",
    step2: "ধাপ ২",
    selectLesson: "লেসন নির্বাচন করুন",
    vocabularyCards: "শব্দ কার্ড",
    practiceThisLesson: "এই লেসন অনুশীলন করুন।",
    selectLessonFirst: "শব্দ কার্ড দেখতে আগে একটি লেসন নির্বাচন করুন।",
    noLessonCards: "এই লেসনে কোনো শব্দ নেই।",
    clickPractice: "অনুশীলন করতে ক্লিক করুন",
    vocabulary: "শব্দ",
    details: "বিস্তারিত",
    clickFlip: "ফ্লিপ করতে কার্ডে ক্লিক করুন",
    clickFlipBack: "ফিরে যেতে কার্ডে ক্লিক করুন",
    closeCard: "কার্ড বন্ধ করুন",
    contentManagement: "কনটেন্ট ম্যানেজমেন্ট",
    adminDashboardCopy:
      "লেসন এবং শব্দের রেকর্ড তৈরি, দেখা এবং আপডেট করুন।",
    lessonAdminCopy: "নতুন লেসন যোগ করুন, লেসন তালিকা দেখুন এবং লেসনের তথ্য আপডেট করুন।",
    vocabularyAdminCopy: "শব্দ যোগ করুন, সব রেকর্ড সার্চ করুন এবং শব্দের তথ্য আপডেট করুন।",
    title: "শিরোনাম",
    description: "বর্ণনা",
    optional: "ঐচ্ছিক",
    saveLesson: "লেসন সেভ করুন",
    saving: "সেভ হচ্ছে...",
    updateLesson: "লেসন আপডেট করুন",
    updating: "আপডেট হচ্ছে...",
    lesson: "লেসন",
    selectALesson: "একটি লেসন নির্বাচন করুন",
    englishWordLabel: "ইংরেজি শব্দ",
    bengaliMeaningLabel: "বাংলা অর্থ",
    exampleOptional: "উদাহরণ বাক্য (ঐচ্ছিক)",
    saveVocabulary: "শব্দ সেভ করুন",
    updateVocabulary: "শব্দ আপডেট করুন",
    browseLessons: "লেসন ব্রাউজ করুন",
    adminPanel: "অ্যাডমিন প্যানেল",
    project: "প্রজেক্ট",
    techStack: "React + Django REST",
    mysqlDatabase: "MySQL ডাটাবেস",
    week3Scope: "Week 3 Final Scope",
    toggleNavigation: "নেভিগেশন মেনু খুলুন/বন্ধ করুন",
    searchSuggestions: "সার্চ সাজেশন",
    builtFor: "শব্দ শেখা এবং কনটেন্ট ম্যানেজমেন্টের জন্য তৈরি",
    projectLine:
      "বাংলা অর্থ, উদাহরণ, সার্চ এবং কনটেন্ট ম্যানেজমেন্টসহ ইংরেজি শব্দ লেসন অনুযায়ী সাজানোর একটি রেসপনসিভ DBMS প্রজেক্ট।",
    partOfSpeech: "পদ (Part of Speech):",
    difficulty: "কঠিনতার মাত্রা",
    easy: "সহজ",
    medium: "মাঝারি",
    hard: "কঠিন",
    allDifficulties: "সব স্তর",
    synonyms: "প্রতিশব্দ:",
    antonyms: "বিপরীত শব্দ:",
    synonymsOptional: "প্রতিশব্দ (ঐচ্ছিক)",
    antonymsOptional: "বিপরীত শব্দ (ঐচ্ছিক)",
    commaSeparatedPlaceholder: "কমা দিয়ে আলাদা করুন, যেমন: Hi, Hey",
    selectOptional: "নির্বাচন করুন (ঐচ্ছিক)",
    noun: "বিশেষ্য",
    verb: "ক্রিয়া",
    adjective: "বিশেষণ",
    adverb: "ক্রিয়া বিশেষণ",
    pronoun: "সর্বনাম",
    preposition: "পদান্বয়ী অব্যয়",
    conjunction: "সংযোজক অব্যয়",
    interjection: "আবেগসূচক শব্দ",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("ej-language") || "en");

  useEffect(() => {
    localStorage.setItem("ej-language", language);
    document.documentElement.lang = language === "bn" ? "bn" : "en";
  }, [language]);

  const value = useMemo(() => {
    function t(key) {
      return translations[language]?.[key] || translations.en[key] || key;
    }

    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "bn" : "en")),
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
